<a href="https://colab.research.google.com/github/Arul-Bhagat/EDA-BACSE301-PRP569/blob/main/Experiment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df_C_marketing= pd.DataFrame({'emp_ID': [2345,6743,6854,3462],'Emp_name': ['A','B','C','D']})
df_C_sales= pd.DataFrame({'emp_ID':[2654,7892,3679,5432],'Emp_name':['E','F','G','H']})
df_R_chemistry= pd.DataFrame({'emp_ID': [3785,9834,1002,4985],'Emp_name':['I','J','K','L']})
df_R_physics= pd.DataFrame({'emp_ID': [4800,923,4572,8003],'Emp_name':['M','N','O','P']})
dfC = pd.concat([df_C_marketing,df_C_sales], ignore_index=True)
dfR = pd.concat([df_R_chemistry,df_R_physics], ignore_index=True)

df = pd.concat([dfC,dfR], axis=1)
df

   emp_ID Emp_name  emp_ID Emp_name
0    2345        A    3785        I
1    6743        B    9834        J
2    6854        C    1002        K
3    3462        D    4985        L
4    2654        E    4800        M
5    7892        F     923        N
6    3679        G    4572        O
7    5432        H    8003        P

In [ ]:
df = dfC.merge(dfR, how='left')
df

   emp_ID Emp_name
0    2345        A
1    6743        B
2    6854        C
3    3462        D
4    2654        E
5    7892        F
6    3679        G
7    5432        H

In [ ]:
df = dfC.merge(dfR, how='right')
df

   emp_ID Emp_name
0    3785        I
1    9834        J
2    1002        K
3    4985        L
4    4800        M
5     923        N
6    4572        O
7    8003        P